<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
    <meta name="generator" content="Aspose.Words for .NET 15.1.0.0" />
    <title></title>
</head>
<body>
<div>
    <h1 style="font-size:22pt; line-height:241%; margin:17pt 0pt 16.5pt; orphans:0; page-break-after:avoid; page-break-inside:avoid; text-align:center; widows:0"><span style="font-family:等线; font-size:22pt; font-weight:bold">网文作品</span><span style="font-family:等线; font-size:22pt; font-weight:bold">申报表</span></h1>
    <div style="text-align:center">
        <table cellspacing="0" cellpadding="0" style="border-collapse:collapse; margin:0 auto; width:431.45pt">
            <tbody>
            <tr style="height:26.95pt">
                <td rowspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:79.5pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">作品</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:85.1pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">名称</span></p></td>
                <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:233.65pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?php echo json_decode($model->works_intro)[0]?></span></p></td>
            </tr>
            <tr style="height:26.95pt">
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:85.1pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">网络链接</span></p></td>
                <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:233.65pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$model->works_link?></span></p></td>
            </tr>
            <tr style="height:26.95pt">
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:85.1pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">阅读量</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:75.2pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$model->click_rate?></span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:68.05pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">评论量</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:68.7pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$model->comment_times?></span></p></td>
            </tr>
            <tr style="height:27.2pt">
                <td rowspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:79.5pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt; letter-spacing:-0.5pt">申报人</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:85.1pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">姓名</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:75.2pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$user->username?></span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:68.05pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">手机</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:68.7pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$user->phone_num?></span></p></td>
            </tr>
            <tr style="height:26.6pt">
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:85.1pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">院系专业</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:75.2pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$user_school?></span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:68.05pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">年级</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:68.7pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$user->grade?></span></p></td>
            </tr>
            <tr style="height:30pt">
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:85.1pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">地址邮编</span></p></td>
                <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:233.65pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$user->address?></span></p></td>
            </tr>
            <tr style="height:25.8pt">
                <td rowspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:79.5pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt; letter-spacing:-0.5pt">指导教师</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:85.1pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">姓名</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:75.2pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$teacher->username?></span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:68.05pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">手机</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:68.7pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$teacher->phone_num?></span></p></td>
            </tr>
            <tr style="height:25.8pt">
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:85.1pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">部门职务</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:75.2pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$teacher->business?></span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:68.05pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">职称</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:68.7pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$teacher->position?></span></p></td>
            </tr>
            <tr style="height:179.95pt">
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:79.5pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt; letter-spacing:1.6pt">作</span></p><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt; letter-spacing:1.6pt">品</span></p><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt; letter-spacing:1.6pt">简</span></p><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt; letter-spacing:1.6pt">介</span></p></td>
                <td colspan="4" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:top; width:329.6pt"><p style="line-height:27pt; margin:0pt"><span style="font-family:楷体_GB2312; font-size:14pt">（限</span><span style="font-family:等线; font-size:14pt">300</span><span style="font-family:楷体_GB2312; font-size:14pt">字以内）</span></p><p style="line-height:27pt; margin:0pt"><span style="font-family:宋体; font-size:14pt"><?php echo json_decode($model->works_intro)[1] ?></span></p><p style="line-height:27pt; margin:0pt"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p><p style="line-height:27pt; margin:0pt"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p><p style="line-height:27pt; margin:0pt"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p></td>
            </tr>
            <tr style="height:155.65pt">
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:79.5pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">学校网络建设管理部门意见</span></p></td>
                <td colspan="4" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:329.6pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"></span></p><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p><p style="line-height:27pt; margin:0pt"><span style="font-family:等线; font-size:14pt">负责人：签章：</span></p><p style="line-height:27pt; margin:0pt; text-align:right"><span style="font-family:等线; font-size:14pt">年</span><span style="font-family:等线; font-size:14pt">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:等线; font-size:14pt">月</span><span style="font-family:等线; font-size:14pt">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:等线; font-size:14pt">日</span></p></td>
            </tr>
            <tr style="height:0pt">
                <td style="width:90.3pt; border:none"></td>
                <td style="width:95.9pt; border:none"></td>
                <td style="width:86pt; border:none"></td>
                <td style="width:78.85pt; border:none"></td>
                <td style="width:79.65pt; border:none"></td>
            </tr>
            </tbody>
        </table>
    </div>
    <p style="margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p>
</div>
</body>
</html>?>