<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
    <meta name="generator" content="Aspose.Words for .NET 15.1.0.0" />
    <style media=print>.PageNext{page-break-after: always;}</style>
    <title></title>
</head>
<body>
<div>
    <h1 style="font-size:22pt; line-height:241%; margin:17pt 0pt 16.5pt; orphans:0; page-break-after:avoid; page-break-inside:avoid; text-align:center; widows:0"><span style="font-family:等线; font-size:22pt; font-weight:bold">校园文化创意作品</span><span style="font-family:等线; font-size:22pt; font-weight:bold">申报表</span></h1>
    <div style="text-align:center">
        <table cellspacing="0" cellpadding="0" style="border-collapse:collapse; margin:0 auto; width:404.55pt">
            <tbody>
            <tr style="height:25.75pt">
                <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:109.9pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">作品名称</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:88.55pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?php echo json_decode($model->works_intro)[0] ?></span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:59.85pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">作品编号</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:102.3pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$model->id?></span></p></td>
            </tr>
            <tr style="height:24.75pt">
                <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:109.9pt"><p style="line-height:14pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">学校名称</span></p></td>
                <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:272.3pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$user->university?></span></p></td>
            </tr>
            <tr style="height:56pt">
                <td rowspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:29.1pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">作品信息</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:70pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">类别</span></p></td>
                <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:272.3pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:楷体_GB2312; font-size:12pt"></span><span style="font-family:等线; font-size:12pt"></span><span style="font-family:楷体_GB2312; font-size:12pt"></span></p><p style="line-height:27pt; margin:0pt"><span style="font-family:宋体; font-size:12pt"></span><span style="font-family:等线; font-size:12pt"></span><span style="font-family:宋体; font-size:14pt"></span><span style="font-family:等线; font-size:12pt"><?php if ($model->works_class2_id==14){ ?>产品</span><span style="font-family:宋体; font-size:12pt">/</span><span style="font-family:等线; font-size:12pt">硬件</span><?php }else{ ?><span style="font-family:宋体; font-size:12pt"></span><span style="font-family:等线; font-size:12pt"></span><span style="font-family:宋体; font-size:14pt"></span><span style="font-family:等线; font-size:12pt">移动应用</span><span style="font-family:宋体; font-size:12pt">/</span><span style="font-family:等线; font-size:12pt">软件</span></p><p style="line-height:27pt; margin:0pt"><span style="font-family:宋体; font-size:12pt"></span><span style="font-family:等线; font-size:12pt"></span><span style="font-family:宋体; font-size:14pt"></span><span style="font-family:等线; font-size:12pt"></span><?php } ?></p></td>
            </tr>
            <tr style="height:28.15pt">
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:70pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">作品形式</span></p></td>
                <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:272.3pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"></span></p></td>
            </tr>
            <tr style="height:28.5pt">
                <td rowspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:29.1pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">申</span></p><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">报</span></p><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">人</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:70pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">姓名</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:88.55pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$user->username?></span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:59.85pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">手机</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:102.3pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$user->phone_num?></span></p></td>
            </tr>
            <tr style="height:27.8pt">
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:70pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">院系专业</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:88.55pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$user_school?></span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:59.85pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">年级</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:102.3pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$user->grade?></span></p></td>
            </tr>
            <tr style="height:28.75pt">
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:70pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">地址邮编</span></p></td>
                <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:272.3pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$user->address?></span></p></td>
            </tr>
            <tr style="height:28.75pt">
                <td rowspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:29.1pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">指导教师</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:70pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">姓名</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:88.55pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$teacher->username?></span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:59.85pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">手机</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:102.3pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$teacher->phone_num?></span></p></td>
            </tr>
            <tr style="height:28.75pt">
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:70pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">部门职务</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:88.55pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$teacher->business?></span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:59.85pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">职称</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:102.3pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$teacher->position?></span></p></td>
            </tr>
            <tr style="height:27pt">
                <td rowspan="7" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:29.1pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">其他成员</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:70pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">姓名</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:88.55pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">院系专业</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:59.85pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">年级</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:102.3pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">手机</span></p></td>
            </tr>
            <?php foreach ($guser as $k => $v){ ?>
            <tr style="height:27pt">
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:70pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$v['username']?></span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:88.55pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$v['user_school']?></span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:59.85pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$v['grade']?></span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:102.3pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:14pt"><?=$v['phone_num']?></span></p></td>
            </tr>
            <?php } ?>
            <tr style="height:0pt">
                <td style="width:39.9pt; border:none"></td>
                <td style="width:80.8pt; border:none"></td>
                <td style="width:99.35pt; border:none"></td>
                <td style="width:70.65pt; border:none"></td>
                <td style="width:113.1pt; border:none"></td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="PageNext"></div>
    <p style="margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p>
    <p style="margin:0pt; orphans:0; text-align:justify; widows:0"><br style="page-break-before:always; clear:both" /></p>
    <p style="margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p>
    <div style="text-align:center">
        <table cellspacing="0" cellpadding="0" style="border-collapse:collapse; margin:0 auto; width:404.55pt">
            <tbody>
            <tr style="height:162.7pt">
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:29.1pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt; letter-spacing:1.6pt">作</span></p><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt; letter-spacing:1.6pt">品</span></p><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt; letter-spacing:1.6pt">简</span></p><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt; letter-spacing:1.6pt">介</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:top; width:353.1pt"><p style="line-height:27pt; margin:0pt"><span style="font-family:楷体_GB2312; font-size:14pt">（限</span><span style="font-family:等线; font-size:14pt">300</span><span style="font-family:楷体_GB2312; font-size:14pt">字以内）</span></p><p style="line-height:27pt; margin:0pt"><span style="font-family:宋体; font-size:14pt"><?php echo json_decode($model->works_intro)[1]?></span></p><p style="line-height:27pt; margin:0pt"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p><p style="line-height:27pt; margin:0pt"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p><p style="line-height:27pt; margin:0pt"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p><p style="line-height:27pt; margin:0pt"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p><p style="line-height:27pt; margin:0pt"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p></td>
            </tr>
            <tr style="height:198.35pt">
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:29.1pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">指导教师意见</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:353.1pt"><p style="line-height:27pt; margin:0pt; text-align:right"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p><p style="line-height:27pt; margin:0pt; text-align:right"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p><p style="line-height:27pt; margin:0pt; text-align:right"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p><p style="line-height:27pt; margin:0pt; text-align:right"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p><p style="line-height:27pt; margin:0pt; text-align:right"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p><p style="line-height:27pt; margin:0pt"><span style="font-family:等线; font-size:14pt">签字：</span></p><p style="line-height:27pt; margin:0pt; text-align:right"><span style="font-family:等线; font-size:14pt">年</span><span style="font-family:等线; font-size:14pt">&nbsp; </span><span style="font-family:等线; font-size:14pt">&nbsp;&nbsp;&nbsp; </span><span style="font-family:等线; font-size:14pt">月</span><span style="font-family:等线; font-size:14pt">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:等线; font-size:14pt">日</span></p></td>
            </tr>
            <tr style="height:197.4pt">
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:29.1pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:14pt">学校网络文化建设管理部门意见</span></p></td>
                <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:353.1pt"><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p><p style="line-height:27pt; margin:0pt; text-align:center"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p><p style="line-height:27pt; margin:0pt"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p><p style="line-height:27pt; margin:0pt"><span style="font-family:等线; font-size:14pt">负责人：签章：</span></p><p style="line-height:27pt; margin:0pt; text-align:right"><span style="font-family:等线; font-size:14pt">年</span><span style="font-family:等线; font-size:14pt">&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:等线; font-size:14pt">月</span><span style="font-family:等线; font-size:14pt">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:等线; font-size:14pt">日</span></p></td>
            </tr>
            </tbody>
        </table>
    </div>
    <p style="margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:等线; font-size:10.5pt">&nbsp;</span></p>
</div>
</body>
</html>?>